{ *****************************************************************************
  * 
  * Sentinel LDK Licensing API Interface
  *
  * Copyright (C) 2021 Thales Group. All rights reserved.
  *
  * Include file for importing external functions
  *
  ***************************************************************************** }

{$IFDEF WIN32}
{$L win32\hasp_windows_delphixe_demo.obj}
{$ENDIF}

{$IFDEF WIN64}
{$L x64\hasp_windows_x64_delphixe_demo.obj}
{$ENDIF}
